### ISSUE TITLE
[TSE] User Trading History

### ISSUE THREAD

**Issue by MWBlocky** [Hu-Fi/Mr.Market-V2#42]
### Implement User Trading History

**Description:**

This task involves implementing a single API endpoint to retrieve the user’s trading history, providing flexibility to filter by various parameters including date range, exchange, asset, type of order, order status, and trade side.

The API will return the user’s executed orders based on the criteria, including optional pagination and sorting.

The existing `Order` entity and enums `MarketOrderType`, `OrderStatus`, and `TradeSideType` will be used.

**Filters**:

- `userId`: The user’s unique identifier.
- `startDate` / `endDate`: A date range to filter the orders.
- `exchangeName`: The name of the exchange where the order was executed.
- `symbol`: The trading pair (e.g., BTC/USD).
- `type`: The type of order (limit, market).
- `status`: The order status (pending, executed, cancelled, failed).
- `side`: The trade side (buy, sell).

### To Do:

- [ ] Implement an endpoint to retrieve trading history for a given user.
- [ ] Support query parameters for filtering by date range, exchange, asset, order type, order status, and trade side.
- [ ] Add pagination support (query parameters: `page`, `limit`).
- [ ] Support sorting by `createdAt`, `price`, or other relevant fields.
- [ ] Ensure the endpoint returns data efficiently with optimized database queries.

### Suggested Endpoint:

**GET /trading-history/user/{userId}**

- **Query Parameters**:
  - `startDate` (optional): Start date for filtering.
  - `endDate` (optional): End date for filtering.
  - `exchangeName` (optional): Filter by exchange name.
  - `symbol` (optional): Filter by trading pair.
  - `type` (optional): Filter by order type (`limit`, `market`).
  - `status` (optional): Filter by order status (`pending`, `executed`, `cancelled`, `failed`).
  - `side` (optional): Filter by trade side (`buy`, `sell`).
  - `page` (optional): Pagination - page number.
  - `limit` (optional): Pagination - number of results per page.
  - `sort` (optional): Field to sort by (e.g., `createdAt`, `price`).

### Deliverables:

- [ ] Fully implemented endpoint with filtering, pagination, and sorting.
- [ ] Unit tests.
- [ ] Documentation.

**Comment by piotrswierzy** [comment]
Estimation: 8 hours
