### ISSUE TITLE
[TSE] Add Direct Exchange Deposits and Withdrawals

### ISSUE THREAD

**Issue by MWBlocky** [Hu-Fi/Mr.Market-V2#44]
### Description
We are extending the deposit and withdrawal functionality for users to directly interact with the exchanges they trade on, bypassing the Mixin bot account. This new functionality will use the CCXT library for handling transfers and will include checks to ensure users have closed trading strategies on a given exchange before allowing withdrawals.

Additionally, we will extend the `user-balance.entity.ts` to include a new field `exchangeName`, which will store the exchange-specific account balance information. This can be used for processes like rebalancing. The system should continuously monitor and update the user's balance status.

### To Do
- [ ] Implement deposit functionality using CCXT, allowing direct deposits to the user's chosen exchange.
- [ ] Implement withdrawal functionality that checks for closed trading strategies on the user's selected exchange before processing the withdrawal.
- [ ] Update `user-balance.entity.ts` to include the `exchangeName` field for tracking balances on specific exchanges.
- [ ] Implement balance status checks to ensure up-to-date user balance information.

### Deliverables
- [ ] All tasks completed
- [ ] Unit tests
- [ ] Documentation

**Comment by piotrswierzy** [comment]
We estimate that this issue will take 2MD
